# .github/workflows/build.yml
name: Build
 
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Determine Target
        id: target
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            echo "::set-output name=target::dev"
          elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "::set-output name=target::main"
          fi

      - name: Build for Dev (if applicable)
        if: steps.target.outputs.target == 'dev'
        run: |
          echo "Building for dev...."
          # Add your dev build logic here

      - name: Build for Main (if applicable)
        if: steps.target.outputs.target == 'main'
        run: |
          echo "Building for main..."
          # Add your main build logic here
