# .github/workflows/build.yml
name: Publish Artifacts for Quicksight and Athena Views
 
on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev
 
jobs:
  publish-artifacts:
    name: Publish Artifacts for Quicksight and Athena Views
    runs-on: ubuntu-latest
