# .github/workflows/pre-tf-steps.yml
name: Pre-tf-steps

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
    conclusion: success

jobs:
  pre-tf:
    name: Pre-Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Determine Target
        id: target
        run: echo "::set-output name=target::${{ github.event.workflow_run.conclusion }}"

      - name: Pre-Terraform for Dev (if applicable)
        if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.workflow_run.head_branch == 'dev'
        run: |
          echo "Pre-Terraform steps for dev..."
          # Add your dev pre-Terraform logic here

      - name: Pre-Terraform for Main (if applicable)
        if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.workflow_run.head_branch == 'main'
        run: |
          echo "Pre-Terraform steps for main..."
          # Add your main pre-Terraform logic here
